/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.htmlbuild.ui.internal.HtmlbuildActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HTMLbuildExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(HtmlbuildActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		HtmlbuildActivator activator = HtmlbuildActivator.getInstance();
		return activator != null ? activator.getInjector(HtmlbuildActivator.ORG_XTEXT_EXAMPLE_MYDSL_HTMLBUILD) : null;
	}

}
