/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.htmlbuild.ui.internal.HtmlbuildActivator;

public class HTMLbuildUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HtmlbuildActivator.getInstance().getInjector("org.xtext.example.mydsl.HTMLbuild");
	}

}
