/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.validation

import org.eclipse.xtext.validation.Check
import org.xtext.example.mydsl.hTMLbuild.Separator
import org.xtext.example.mydsl.hTMLbuild.Div
import org.xtext.example.mydsl.hTMLbuild.Next
import org.xtext.example.mydsl.hTMLbuild.Then

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class HTMLbuildValidator extends AbstractHTMLbuildValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					HTMLbuildPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def checkSeparatorRatio(Separator separator) {
		if (separator.hasratio) {
			var ratio_sum = 0
			if (separator.ratios.size > 1) {
				warning("Separator has 2 Ratios (this is usually only the first Separator).", null)
			}
			for (ratio : separator.ratios) {
				if (ratio.intValue > 100 || ratio.intValue < 0) {
					error("Separator Ratios must be between [0,100]%.", null)
				}
				ratio_sum += ratio.intValue
			}
			if (ratio_sum > 100) {
				error("Ratios > 100%.", null)
			}
		}
	}
}