/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.hTMLbuild;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Div</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.hTMLbuild.Div#getDiv_id <em>Div id</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.hTMLbuild.Div#getDivelements <em>Divelements</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.hTMLbuild.Div#getSeparators <em>Separators</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getDiv()
 * @model
 * @generated
 */
public interface Div extends Type, Element
{
  /**
   * Returns the value of the '<em><b>Div id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Div id</em>' attribute.
   * @see #setDiv_id(String)
   * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getDiv_Div_id()
   * @model
   * @generated
   */
  String getDiv_id();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.hTMLbuild.Div#getDiv_id <em>Div id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Div id</em>' attribute.
   * @see #getDiv_id()
   * @generated
   */
  void setDiv_id(String value);

  /**
   * Returns the value of the '<em><b>Divelements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.hTMLbuild.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Divelements</em>' containment reference list.
   * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getDiv_Divelements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getDivelements();

  /**
   * Returns the value of the '<em><b>Separators</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.hTMLbuild.Separator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Separators</em>' containment reference list.
   * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getDiv_Separators()
   * @model containment="true"
   * @generated
   */
  EList<Separator> getSeparators();

} // Div
