/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.hTMLbuild;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildFactory
 * @model kind="package"
 * @generated
 */
public interface HTMLbuildPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "hTMLbuild";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/HTMLbuild";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "hTMLbuild";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HTMLbuildPackage eINSTANCE = org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.hTMLbuild.impl.ModelImpl
   * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.hTMLbuild.impl.TypeImpl
   * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.StyleImpl <em>Style</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.hTMLbuild.impl.StyleImpl
   * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getStyle()
   * @generated
   */
  int STYLE = 2;

  /**
   * The feature id for the '<em><b>Style id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE__STYLE_ID = TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Link</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE__LINK = TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Newlink</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE__NEWLINK = TYPE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Style</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.ContentImpl <em>Content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.hTMLbuild.impl.ContentImpl
   * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getContent()
   * @generated
   */
  int CONTENT = 3;

  /**
   * The feature id for the '<em><b>Elem</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__ELEM = TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__NAME = TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_FEATURE_COUNT = TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.TextImpl <em>Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.hTMLbuild.impl.TextImpl
   * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getText()
   * @generated
   */
  int TEXT = 4;

  /**
   * The feature id for the '<em><b>Elem</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__ELEM = CONTENT__ELEM;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__NAME = CONTENT__NAME;

  /**
   * The feature id for the '<em><b>H1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__H1 = CONTENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>H2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__H2 = CONTENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>H3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__H3 = CONTENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FEATURE_COUNT = CONTENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.ImageImpl <em>Image</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.hTMLbuild.impl.ImageImpl
   * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getImage()
   * @generated
   */
  int IMAGE = 5;

  /**
   * The feature id for the '<em><b>Elem</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__ELEM = CONTENT__ELEM;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__NAME = CONTENT__NAME;

  /**
   * The feature id for the '<em><b>Link</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__LINK = CONTENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Newlink</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__NEWLINK = CONTENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Image</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_FEATURE_COUNT = CONTENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.LinkImpl <em>Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.hTMLbuild.impl.LinkImpl
   * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getLink()
   * @generated
   */
  int LINK = 6;

  /**
   * The feature id for the '<em><b>Elem</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__ELEM = CONTENT__ELEM;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__NAME = CONTENT__NAME;

  /**
   * The feature id for the '<em><b>Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__ADDRESS = CONTENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Anchor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__ANCHOR = CONTENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Linktext</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__LINKTEXT = CONTENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_FEATURE_COUNT = CONTENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.hTMLbuild.impl.ElementImpl
   * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 7;

  /**
   * The feature id for the '<em><b>Elem</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__ELEM = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.DivImpl <em>Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.hTMLbuild.impl.DivImpl
   * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getDiv()
   * @generated
   */
  int DIV = 8;

  /**
   * The feature id for the '<em><b>Elem</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__ELEM = TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Div id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__DIV_ID = TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Divelements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__DIVELEMENTS = TYPE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Separators</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__SEPARATORS = TYPE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_FEATURE_COUNT = TYPE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.SeparatorImpl <em>Separator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.hTMLbuild.impl.SeparatorImpl
   * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getSeparator()
   * @generated
   */
  int SEPARATOR = 9;

  /**
   * The feature id for the '<em><b>Hasratio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEPARATOR__HASRATIO = 0;

  /**
   * The feature id for the '<em><b>Ratios</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEPARATOR__RATIOS = 1;

  /**
   * The number of structural features of the '<em>Separator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEPARATOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.NextImpl <em>Next</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.hTMLbuild.impl.NextImpl
   * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getNext()
   * @generated
   */
  int NEXT = 10;

  /**
   * The feature id for the '<em><b>Hasratio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEXT__HASRATIO = SEPARATOR__HASRATIO;

  /**
   * The feature id for the '<em><b>Ratios</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEXT__RATIOS = SEPARATOR__RATIOS;

  /**
   * The number of structural features of the '<em>Next</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEXT_FEATURE_COUNT = SEPARATOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.ThenImpl <em>Then</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.hTMLbuild.impl.ThenImpl
   * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getThen()
   * @generated
   */
  int THEN = 11;

  /**
   * The feature id for the '<em><b>Hasratio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN__HASRATIO = SEPARATOR__HASRATIO;

  /**
   * The feature id for the '<em><b>Ratios</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN__RATIOS = SEPARATOR__RATIOS;

  /**
   * The number of structural features of the '<em>Then</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN_FEATURE_COUNT = SEPARATOR_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.hTMLbuild.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.hTMLbuild.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.hTMLbuild.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.hTMLbuild.Style <em>Style</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Style</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Style
   * @generated
   */
  EClass getStyle();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.hTMLbuild.Style#getStyle_id <em>Style id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Style id</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Style#getStyle_id()
   * @see #getStyle()
   * @generated
   */
  EAttribute getStyle_Style_id();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.hTMLbuild.Style#getLink <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Link</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Style#getLink()
   * @see #getStyle()
   * @generated
   */
  EReference getStyle_Link();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.hTMLbuild.Style#getNewlink <em>Newlink</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Newlink</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Style#getNewlink()
   * @see #getStyle()
   * @generated
   */
  EReference getStyle_Newlink();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.hTMLbuild.Content <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Content</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Content
   * @generated
   */
  EClass getContent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.hTMLbuild.Content#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Content#getName()
   * @see #getContent()
   * @generated
   */
  EAttribute getContent_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.hTMLbuild.Text <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Text
   * @generated
   */
  EClass getText();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.hTMLbuild.Text#isH1 <em>H1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>H1</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Text#isH1()
   * @see #getText()
   * @generated
   */
  EAttribute getText_H1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.hTMLbuild.Text#isH2 <em>H2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>H2</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Text#isH2()
   * @see #getText()
   * @generated
   */
  EAttribute getText_H2();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.hTMLbuild.Text#isH3 <em>H3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>H3</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Text#isH3()
   * @see #getText()
   * @generated
   */
  EAttribute getText_H3();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.hTMLbuild.Image <em>Image</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Image</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Image
   * @generated
   */
  EClass getImage();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.hTMLbuild.Image#getLink <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Link</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Image#getLink()
   * @see #getImage()
   * @generated
   */
  EReference getImage_Link();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.hTMLbuild.Image#getNewlink <em>Newlink</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Newlink</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Image#getNewlink()
   * @see #getImage()
   * @generated
   */
  EReference getImage_Newlink();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.hTMLbuild.Link <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Link</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Link
   * @generated
   */
  EClass getLink();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.hTMLbuild.Link#getAddress <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Address</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Link#getAddress()
   * @see #getLink()
   * @generated
   */
  EAttribute getLink_Address();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.hTMLbuild.Link#getAnchor <em>Anchor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Anchor</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Link#getAnchor()
   * @see #getLink()
   * @generated
   */
  EReference getLink_Anchor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.hTMLbuild.Link#getLinktext <em>Linktext</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Linktext</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Link#getLinktext()
   * @see #getLink()
   * @generated
   */
  EAttribute getLink_Linktext();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.hTMLbuild.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.hTMLbuild.Element#getElem <em>Elem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Elem</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Element#getElem()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Elem();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.hTMLbuild.Div <em>Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Div</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Div
   * @generated
   */
  EClass getDiv();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.hTMLbuild.Div#getDiv_id <em>Div id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Div id</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Div#getDiv_id()
   * @see #getDiv()
   * @generated
   */
  EAttribute getDiv_Div_id();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.hTMLbuild.Div#getDivelements <em>Divelements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Divelements</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Div#getDivelements()
   * @see #getDiv()
   * @generated
   */
  EReference getDiv_Divelements();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.hTMLbuild.Div#getSeparators <em>Separators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Separators</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Div#getSeparators()
   * @see #getDiv()
   * @generated
   */
  EReference getDiv_Separators();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.hTMLbuild.Separator <em>Separator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Separator</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Separator
   * @generated
   */
  EClass getSeparator();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.hTMLbuild.Separator#isHasratio <em>Hasratio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hasratio</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Separator#isHasratio()
   * @see #getSeparator()
   * @generated
   */
  EAttribute getSeparator_Hasratio();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.hTMLbuild.Separator#getRatios <em>Ratios</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Ratios</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Separator#getRatios()
   * @see #getSeparator()
   * @generated
   */
  EAttribute getSeparator_Ratios();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.hTMLbuild.Next <em>Next</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Next</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Next
   * @generated
   */
  EClass getNext();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.hTMLbuild.Then <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Then</em>'.
   * @see org.xtext.example.mydsl.hTMLbuild.Then
   * @generated
   */
  EClass getThen();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  HTMLbuildFactory getHTMLbuildFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.hTMLbuild.impl.ModelImpl
     * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.hTMLbuild.impl.TypeImpl
     * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.StyleImpl <em>Style</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.hTMLbuild.impl.StyleImpl
     * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getStyle()
     * @generated
     */
    EClass STYLE = eINSTANCE.getStyle();

    /**
     * The meta object literal for the '<em><b>Style id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STYLE__STYLE_ID = eINSTANCE.getStyle_Style_id();

    /**
     * The meta object literal for the '<em><b>Link</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STYLE__LINK = eINSTANCE.getStyle_Link();

    /**
     * The meta object literal for the '<em><b>Newlink</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STYLE__NEWLINK = eINSTANCE.getStyle_Newlink();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.ContentImpl <em>Content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.hTMLbuild.impl.ContentImpl
     * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getContent()
     * @generated
     */
    EClass CONTENT = eINSTANCE.getContent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENT__NAME = eINSTANCE.getContent_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.TextImpl <em>Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.hTMLbuild.impl.TextImpl
     * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getText()
     * @generated
     */
    EClass TEXT = eINSTANCE.getText();

    /**
     * The meta object literal for the '<em><b>H1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT__H1 = eINSTANCE.getText_H1();

    /**
     * The meta object literal for the '<em><b>H2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT__H2 = eINSTANCE.getText_H2();

    /**
     * The meta object literal for the '<em><b>H3</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT__H3 = eINSTANCE.getText_H3();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.ImageImpl <em>Image</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.hTMLbuild.impl.ImageImpl
     * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getImage()
     * @generated
     */
    EClass IMAGE = eINSTANCE.getImage();

    /**
     * The meta object literal for the '<em><b>Link</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMAGE__LINK = eINSTANCE.getImage_Link();

    /**
     * The meta object literal for the '<em><b>Newlink</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMAGE__NEWLINK = eINSTANCE.getImage_Newlink();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.LinkImpl <em>Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.hTMLbuild.impl.LinkImpl
     * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getLink()
     * @generated
     */
    EClass LINK = eINSTANCE.getLink();

    /**
     * The meta object literal for the '<em><b>Address</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK__ADDRESS = eINSTANCE.getLink_Address();

    /**
     * The meta object literal for the '<em><b>Anchor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINK__ANCHOR = eINSTANCE.getLink_Anchor();

    /**
     * The meta object literal for the '<em><b>Linktext</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK__LINKTEXT = eINSTANCE.getLink_Linktext();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.hTMLbuild.impl.ElementImpl
     * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Elem</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__ELEM = eINSTANCE.getElement_Elem();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.DivImpl <em>Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.hTMLbuild.impl.DivImpl
     * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getDiv()
     * @generated
     */
    EClass DIV = eINSTANCE.getDiv();

    /**
     * The meta object literal for the '<em><b>Div id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIV__DIV_ID = eINSTANCE.getDiv_Div_id();

    /**
     * The meta object literal for the '<em><b>Divelements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIV__DIVELEMENTS = eINSTANCE.getDiv_Divelements();

    /**
     * The meta object literal for the '<em><b>Separators</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIV__SEPARATORS = eINSTANCE.getDiv_Separators();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.SeparatorImpl <em>Separator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.hTMLbuild.impl.SeparatorImpl
     * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getSeparator()
     * @generated
     */
    EClass SEPARATOR = eINSTANCE.getSeparator();

    /**
     * The meta object literal for the '<em><b>Hasratio</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SEPARATOR__HASRATIO = eINSTANCE.getSeparator_Hasratio();

    /**
     * The meta object literal for the '<em><b>Ratios</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SEPARATOR__RATIOS = eINSTANCE.getSeparator_Ratios();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.NextImpl <em>Next</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.hTMLbuild.impl.NextImpl
     * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getNext()
     * @generated
     */
    EClass NEXT = eINSTANCE.getNext();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.hTMLbuild.impl.ThenImpl <em>Then</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.hTMLbuild.impl.ThenImpl
     * @see org.xtext.example.mydsl.hTMLbuild.impl.HTMLbuildPackageImpl#getThen()
     * @generated
     */
    EClass THEN = eINSTANCE.getThen();

  }

} //HTMLbuildPackage
