/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.hTMLbuild;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Image</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.hTMLbuild.Image#getLink <em>Link</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.hTMLbuild.Image#getNewlink <em>Newlink</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getImage()
 * @model
 * @generated
 */
public interface Image extends Content
{
  /**
   * Returns the value of the '<em><b>Link</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link</em>' reference.
   * @see #setLink(Link)
   * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getImage_Link()
   * @model
   * @generated
   */
  Link getLink();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.hTMLbuild.Image#getLink <em>Link</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link</em>' reference.
   * @see #getLink()
   * @generated
   */
  void setLink(Link value);

  /**
   * Returns the value of the '<em><b>Newlink</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Newlink</em>' containment reference.
   * @see #setNewlink(Link)
   * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getImage_Newlink()
   * @model containment="true"
   * @generated
   */
  Link getNewlink();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.hTMLbuild.Image#getNewlink <em>Newlink</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Newlink</em>' containment reference.
   * @see #getNewlink()
   * @generated
   */
  void setNewlink(Link value);

} // Image
