/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.hTMLbuild;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.hTMLbuild.Link#getAddress <em>Address</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.hTMLbuild.Link#getAnchor <em>Anchor</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.hTMLbuild.Link#getLinktext <em>Linktext</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getLink()
 * @model
 * @generated
 */
public interface Link extends Content
{
  /**
   * Returns the value of the '<em><b>Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Address</em>' attribute.
   * @see #setAddress(String)
   * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getLink_Address()
   * @model
   * @generated
   */
  String getAddress();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.hTMLbuild.Link#getAddress <em>Address</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Address</em>' attribute.
   * @see #getAddress()
   * @generated
   */
  void setAddress(String value);

  /**
   * Returns the value of the '<em><b>Anchor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Anchor</em>' reference.
   * @see #setAnchor(Content)
   * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getLink_Anchor()
   * @model
   * @generated
   */
  Content getAnchor();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.hTMLbuild.Link#getAnchor <em>Anchor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Anchor</em>' reference.
   * @see #getAnchor()
   * @generated
   */
  void setAnchor(Content value);

  /**
   * Returns the value of the '<em><b>Linktext</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Linktext</em>' attribute.
   * @see #setLinktext(String)
   * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getLink_Linktext()
   * @model
   * @generated
   */
  String getLinktext();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.hTMLbuild.Link#getLinktext <em>Linktext</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Linktext</em>' attribute.
   * @see #getLinktext()
   * @generated
   */
  void setLinktext(String value);

} // Link
