/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.hTMLbuild;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Next</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getNext()
 * @model
 * @generated
 */
public interface Next extends Separator
{
} // Next
