/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.hTMLbuild;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Separator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.hTMLbuild.Separator#isHasratio <em>Hasratio</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.hTMLbuild.Separator#getRatios <em>Ratios</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getSeparator()
 * @model
 * @generated
 */
public interface Separator extends EObject
{
  /**
   * Returns the value of the '<em><b>Hasratio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hasratio</em>' attribute.
   * @see #setHasratio(boolean)
   * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getSeparator_Hasratio()
   * @model
   * @generated
   */
  boolean isHasratio();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.hTMLbuild.Separator#isHasratio <em>Hasratio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hasratio</em>' attribute.
   * @see #isHasratio()
   * @generated
   */
  void setHasratio(boolean value);

  /**
   * Returns the value of the '<em><b>Ratios</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ratios</em>' attribute list.
   * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getSeparator_Ratios()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getRatios();

} // Separator
