/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.hTMLbuild;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.hTMLbuild.Text#isH1 <em>H1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.hTMLbuild.Text#isH2 <em>H2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.hTMLbuild.Text#isH3 <em>H3</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getText()
 * @model
 * @generated
 */
public interface Text extends Content
{
  /**
   * Returns the value of the '<em><b>H1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>H1</em>' attribute.
   * @see #setH1(boolean)
   * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getText_H1()
   * @model
   * @generated
   */
  boolean isH1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.hTMLbuild.Text#isH1 <em>H1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>H1</em>' attribute.
   * @see #isH1()
   * @generated
   */
  void setH1(boolean value);

  /**
   * Returns the value of the '<em><b>H2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>H2</em>' attribute.
   * @see #setH2(boolean)
   * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getText_H2()
   * @model
   * @generated
   */
  boolean isH2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.hTMLbuild.Text#isH2 <em>H2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>H2</em>' attribute.
   * @see #isH2()
   * @generated
   */
  void setH2(boolean value);

  /**
   * Returns the value of the '<em><b>H3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>H3</em>' attribute.
   * @see #setH3(boolean)
   * @see org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage#getText_H3()
   * @model
   * @generated
   */
  boolean isH3();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.hTMLbuild.Text#isH3 <em>H3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>H3</em>' attribute.
   * @see #isH3()
   * @generated
   */
  void setH3(boolean value);

} // Text
