/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.hTMLbuild.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.hTMLbuild.HTMLbuildPackage;
import org.xtext.example.mydsl.hTMLbuild.Next;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Next</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NextImpl extends SeparatorImpl implements Next
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NextImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HTMLbuildPackage.Literals.NEXT;
  }

} //NextImpl
